### ISSUE TITLE
Path is not always on host root

### ISSUE THREAD

**Issue by lucaboesch** [bschur/moodle-qtype_uml#19]
This
https://github.com/bschur/moodle-qtype_uml/blob/dd62720a95e58dd137cf2bf19ad805ada482cf03/dist/loader.js#L3
`mainScript.src = '/question/type/uml/dist/main.js';`
would break in my place. My Moodle instance is installed in a subfolder mdk/stable_402.
I believe those elements of the path should be taken into account. You can't assume there are no subfolders and Moodle is installed inside the root of a server.

**Comment by arisjavet-personal** [comment]
@lucaboesch In my research I couldn't find a way to support custom-build esm modules loaded with `type=module` into moodle. They only support their ASM builder. This one doesn't fit our need since we use a framework to build our webcomponent and we already have our javascript binaries.
Do you know of a way to load esm modules?

**Comment by arisjavet-personal** [comment]
@lucaboesch found potential fix. Done on https://github.com/bschur/moodle-qtype_uml/pull/23

**Comment by lucaboesch** [comment]
Brilliant!
